import type { Product } from "./types"

// Productos mockup para desarrollo sin base de datos
export const mockProducts: Product[] = [
  {
    id: "aceite-cbd-80-local",
    name: "Aceite Natural Full Spectrum 80%",
    slug: "aceite-natural-80-full-spectrum",
    description: "Aceite natural cultivado en Argentina con espectro completo",
    longDescription: "Nuestro aceite Full Spectrum 80% es cultivado y procesado en Argentina con los más altos estándares de calidad.\n\n✔️ 80% de concentración\n✔️ Full Spectrum (espectro completo)\n✔️ Sin aditivos ni químicos\n✔️ Extracción natural\n✔️ Ideal para empezar tu rutina\n\nUso recomendado: 2-3 gotas sublinguales, mantener bajo la lengua 60-90 segundos antes de tragar. Comenzar de menos a más.",
    long_description: "Aceite de máxima calidad cultivado localmente. Full Spectrum con todos los cannabinoides naturales.",
    price: 50000,
    compareAt: 75000,
    compare_at: 75000,
    category: "Aceites",
    sizes: ["30ml", "60ml"],
    colors: ["Natural"],
    images: [
      "/uploads/hero-aceite.jpg",
      "/uploads/beneficios-cbd.png",
      "/placeholder.svg"
    ],
    videos: [],
    tags: ["local", "full-spectrum", "bestseller", "natural"],
    stock: 50,
    featured: true,
    sku: "ACE-80-FS-30",
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString(),
    is_on_sale: true,
    sale_price: 50000,
  },
  {
    id: "premium-hemp-oil-usa",
    name: "Premium Hemp Oil USA 12.000mg",
    slug: "premium-hemp-oil-12000mg",
    description: "Aceite premium importado de Estados Unidos con máxima concentración",
    longDescription: "Premium Hemp Oil importado directamente de EE.UU. con la más alta concentración disponible.\n\n✔️ 12.000mg de concentración total\n✔️ Importado de Estados Unidos\n✔️ Extracción por CO₂ supercrítico\n✔️ Gotero calibrado para dosificación precisa\n✔️ Producción en batch pequeño\n✔️ Más concentración por mL\n\nIdeal para usuarios experimentados que buscan máxima potencia y resultados más notables.\n\nUso: Comenzar con 1-2 gotas sublinguales, ajustar según necesidad.",
    long_description: "Aceite premium importado con la máxima concentración del mercado.",
    price: 50000,
    compareAt: 85000,
    compare_at: 85000,
    category: "Aceites",
    sizes: ["60ml"],
    colors: ["Premium"],
    images: [
      "/uploads/gel-crema.png",
      "/placeholder.svg"
    ],
    videos: [],
    tags: ["premium", "importado", "alta-concentracion", "usa"],
    stock: 25,
    featured: true,
    sku: "PHO-12000-60",
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString(),
    is_on_sale: false,
  },
  {
    id: "capsulas-cbd-25mg",
    name: "Cápsulas Naturales 25mg",
    slug: "capsulas-naturales-25mg",
    description: "Cápsulas con dosificación exacta, prácticas y discretas",
    longDescription: "Nuestras cápsulas ofrecen la forma más práctica de incorporar bienestar a tu rutina.\n\n✔️ 25mg por cápsula\n✔️ Dosificación exacta y constante\n✔️ Fácil de transportar\n✔️ Sin sabor\n✔️ Ideal para viajes\n✔️ Presentación discreta\n\nIdeal para personas que buscan practicidad y dosificación precisa.\n\nUso: 1-2 cápsulas al día con agua, preferiblemente con alimentos.",
    long_description: "Cápsulas prácticas para dosificación exacta y uso diario.",
    price: 50000,
    category: "Cápsulas",
    sizes: ["30 unidades"],
    colors: ["Natural"],
    images: [
      "/placeholder.svg"
    ],
    videos: [],
    tags: ["capsulas", "practico", "viaje", "dosificacion-exacta"],
    stock: 100,
    featured: false,
    sku: "CAP-25-30",
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "gomitas-cbd-10mg",
    name: "Gomitas Naturales 10mg",
    slug: "gomitas-naturales-10mg",
    description: "Gomitas con sabor natural, momento placentero de autocuidado",
    longDescription: "Incorporá bienestar a tu rutina de la forma más rica y placentera.\n\n✔️ 10mg por gomita\n✔️ Sabor natural agradable\n✔️ Sin azúcar añadida\n✔️ Momento de autocuidado\n✔️ Dosificación simple\n✔️ Presentación atractiva\n\nIdeal para quienes buscan una forma agradable de bienestar diario.\n\nUso: 1-2 gomitas al día. Comenzar con 1 gomita y ajustar según necesidad. Masticar bien antes de tragar.",
    long_description: "Gomitas de sabor agradable para un momento de bienestar placentero.",
    price: 50000,
    category: "Gomitas",
    sizes: ["30 unidades"],
    colors: ["Natural"],
    images: [
      "/placeholder.svg"
    ],
    videos: [],
    tags: ["gomitas", "sabor", "autocuidado", "practico"],
    stock: 75,
    featured: false,
    sku: "GOM-10-30",
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
]

